meta_product_name: "Ethikly"
meta_title: "Ethikly - Un job éthique à portée de clic"
meta_description: "Recherche d'emploi axée sur les valeurs morales et sociétales des entreprises"
meta_image: "logo_main.png" # should exist in `app/assets/images/`
